# Define Dynamixel model
MY_DXL = 'X_SERIES'  # X330 (5.0 V recommended), X430, X540, 2X430
# Control table address
ADDR_TORQUE_ENABLE = 64
ADDR_GOAL_POSITION = 116
LEN_GOAL_POSITION = 4  # Data Byte Length
ADDR_PRESENT_POSITION = 132
LEN_PRESENT_POSITION = 4  # Data Byte Length
ADDR_PROFILE_VELOCITY = 112  # Profile Velocity
ADDR_PROFILE_ACCELERATION = 108  # Profile Acceleration
# Movement positions
DXL_MINIMUM_POSITION_VALUE_HB = 1210
DXL_MAXIMUM_POSITION_VALUE_HB = 2200
DXL_MINIMUM_POSITION_VALUE_GD1 = 1450
DXL_MAXIMUM_POSITION_VALUE_GD1 = 2650
DXL_MINIMUM_POSITION_VALUE_GD3 = 1200
DXL_MAXIMUM_POSITION_VALUE_GD3 = 2400
DXL_MINIMUM_POSITION_VALUE_GD5 = 1400
DXL_MAXIMUM_POSITION_VALUE_GD5 = 2700
DXL_MINIMUM_POSITION_VALUE_GD7 = 1300
DXL_MAXIMUM_POSITION_VALUE_GD7 = 2600
DXL_MINIMUM_POSITION_VALUE_GD9 = 1450
DXL_MAXIMUM_POSITION_VALUE_GD9 = 2650
DXL_MINIMUM_POSITION_VALUE_GD11 = 1450
DXL_MAXIMUM_POSITION_VALUE_GD11 = 2650
# Set the profile velocity and acceleration
PROFILE_VELOCITY = 85
PROFILE_ACCELERATION = 40
BAUDRATE = 1000000
# Protocol version
PROTOCOL_VERSION = 2.0
# Dynamixel IDs for lift and rotate
LIFT_SERVOS = [2, 4, 6, 8, 10, 12]
ROTATE_SERVOS = [1, 3, 5, 7, 9, 11]
# Port
DEVICENAME = '/dev/ttyUSB0'
#DEVICENAME = 'COM3'
TORQUE_ENABLE = 1
TORQUE_DISABLE = 0
DXL_MOVING_STATUS_THRESHOLD = 100
ESC_ASCII_VALUE = 0x1b

lift_positions = (DXL_MINIMUM_POSITION_VALUE_HB, DXL_MAXIMUM_POSITION_VALUE_HB)

rotate_positions = {
    1: (DXL_MINIMUM_POSITION_VALUE_GD1, DXL_MAXIMUM_POSITION_VALUE_GD1),
    3: (DXL_MINIMUM_POSITION_VALUE_GD3, DXL_MAXIMUM_POSITION_VALUE_GD3),
    5: (DXL_MINIMUM_POSITION_VALUE_GD5, DXL_MAXIMUM_POSITION_VALUE_GD5),
    7: (DXL_MINIMUM_POSITION_VALUE_GD7, DXL_MAXIMUM_POSITION_VALUE_GD7),
    9: (DXL_MINIMUM_POSITION_VALUE_GD9, DXL_MAXIMUM_POSITION_VALUE_GD9),
    11: (DXL_MINIMUM_POSITION_VALUE_GD11, DXL_MAXIMUM_POSITION_VALUE_GD11)
}